/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rcs.configuration.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rcs.configuration.model.Configuration;
import com.rcs.configuration.service.ConfigurationLocalServiceUtil;

/**
 * The extended model base implementation for the Configuration service. Represents a row in the &quot;configuration_Configuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfigurationImpl}.
 * </p>
 *
 * @author rotterdamcs
 * @see ConfigurationImpl
 * @see com.rcs.configuration.model.Configuration
 * @generated
 */
public abstract class ConfigurationBaseImpl extends ConfigurationModelImpl
	implements Configuration {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a configuration model instance should use the {@link Configuration} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ConfigurationLocalServiceUtil.addConfiguration(this);
		}
		else {
			ConfigurationLocalServiceUtil.updateConfiguration(this);
		}
	}
}