/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.configuration.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rcs.configuration.model.Configuration;
import com.rcs.configuration.model.ConfigurationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Configuration service. Represents a row in the &quot;configuration_Configuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rcs.configuration.model.ConfigurationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfigurationImpl}.
 * </p>
 *
 * @author rotterdamcs
 * @see ConfigurationImpl
 * @see com.rcs.configuration.model.Configuration
 * @see com.rcs.configuration.model.ConfigurationModel
 * @generated
 */
public class ConfigurationModelImpl extends BaseModelImpl<Configuration>
	implements ConfigurationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a configuration model instance should use the {@link com.rcs.configuration.model.Configuration} interface instead.
	 */
	public static final String TABLE_NAME = "configuration_Configuration";
	public static final Object[][] TABLE_COLUMNS = {
			{ "configurationId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "propertyname", Types.VARCHAR },
			{ "propertyvalue", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table configuration_Configuration (configurationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,propertyname VARCHAR(255) null,propertyvalue VARCHAR(255) null)";
	public static final String TABLE_SQL_DROP = "drop table configuration_Configuration";
	public static final String ORDER_BY_JPQL = " ORDER BY configuration.configurationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY configuration_Configuration.configurationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rcs.configuration.model.Configuration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rcs.configuration.model.Configuration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rcs.configuration.model.Configuration"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long PROPERTYNAME_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rcs.configuration.model.Configuration"));

	public ConfigurationModelImpl() {
	}

	public long getPrimaryKey() {
		return _configurationId;
	}

	public void setPrimaryKey(long primaryKey) {
		setConfigurationId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_configurationId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Configuration.class;
	}

	public String getModelClassName() {
		return Configuration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("configurationId", getConfigurationId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("propertyname", getPropertyname());
		attributes.put("propertyvalue", getPropertyvalue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long configurationId = (Long)attributes.get("configurationId");

		if (configurationId != null) {
			setConfigurationId(configurationId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String propertyname = (String)attributes.get("propertyname");

		if (propertyname != null) {
			setPropertyname(propertyname);
		}

		String propertyvalue = (String)attributes.get("propertyvalue");

		if (propertyvalue != null) {
			setPropertyvalue(propertyvalue);
		}
	}

	public long getConfigurationId() {
		return _configurationId;
	}

	public void setConfigurationId(long configurationId) {
		_columnBitmask = -1L;

		_configurationId = configurationId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getPropertyname() {
		if (_propertyname == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyname;
		}
	}

	public void setPropertyname(String propertyname) {
		_columnBitmask |= PROPERTYNAME_COLUMN_BITMASK;

		if (_originalPropertyname == null) {
			_originalPropertyname = _propertyname;
		}

		_propertyname = propertyname;
	}

	public String getOriginalPropertyname() {
		return GetterUtil.getString(_originalPropertyname);
	}

	public String getPropertyvalue() {
		if (_propertyvalue == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyvalue;
		}
	}

	public void setPropertyvalue(String propertyvalue) {
		_propertyvalue = propertyvalue;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Configuration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Configuration toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Configuration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ConfigurationImpl configurationImpl = new ConfigurationImpl();

		configurationImpl.setConfigurationId(getConfigurationId());
		configurationImpl.setGroupId(getGroupId());
		configurationImpl.setCompanyId(getCompanyId());
		configurationImpl.setUserId(getUserId());
		configurationImpl.setUserName(getUserName());
		configurationImpl.setCreateDate(getCreateDate());
		configurationImpl.setModifiedDate(getModifiedDate());
		configurationImpl.setPropertyname(getPropertyname());
		configurationImpl.setPropertyvalue(getPropertyvalue());

		configurationImpl.resetOriginalValues();

		return configurationImpl;
	}

	public int compareTo(Configuration configuration) {
		int value = 0;

		if (getConfigurationId() < configuration.getConfigurationId()) {
			value = -1;
		}
		else if (getConfigurationId() > configuration.getConfigurationId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Configuration configuration = null;

		try {
			configuration = (Configuration)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = configuration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ConfigurationModelImpl configurationModelImpl = this;

		configurationModelImpl._originalGroupId = configurationModelImpl._groupId;

		configurationModelImpl._setOriginalGroupId = false;

		configurationModelImpl._originalCompanyId = configurationModelImpl._companyId;

		configurationModelImpl._setOriginalCompanyId = false;

		configurationModelImpl._originalPropertyname = configurationModelImpl._propertyname;

		configurationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Configuration> toCacheModel() {
		ConfigurationCacheModel configurationCacheModel = new ConfigurationCacheModel();

		configurationCacheModel.configurationId = getConfigurationId();

		configurationCacheModel.groupId = getGroupId();

		configurationCacheModel.companyId = getCompanyId();

		configurationCacheModel.userId = getUserId();

		configurationCacheModel.userName = getUserName();

		String userName = configurationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			configurationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			configurationCacheModel.createDate = createDate.getTime();
		}
		else {
			configurationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			configurationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			configurationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		configurationCacheModel.propertyname = getPropertyname();

		String propertyname = configurationCacheModel.propertyname;

		if ((propertyname != null) && (propertyname.length() == 0)) {
			configurationCacheModel.propertyname = null;
		}

		configurationCacheModel.propertyvalue = getPropertyvalue();

		String propertyvalue = configurationCacheModel.propertyvalue;

		if ((propertyvalue != null) && (propertyvalue.length() == 0)) {
			configurationCacheModel.propertyvalue = null;
		}

		return configurationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{configurationId=");
		sb.append(getConfigurationId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", propertyname=");
		sb.append(getPropertyname());
		sb.append(", propertyvalue=");
		sb.append(getPropertyvalue());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rcs.configuration.model.Configuration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>configurationId</column-name><column-value><![CDATA[");
		sb.append(getConfigurationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyname</column-name><column-value><![CDATA[");
		sb.append(getPropertyname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyvalue</column-name><column-value><![CDATA[");
		sb.append(getPropertyvalue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Configuration.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Configuration.class
		};
	private long _configurationId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _propertyname;
	private String _originalPropertyname;
	private String _propertyvalue;
	private long _columnBitmask;
	private Configuration _escapedModelProxy;
}